project:
  type: website

website:
  title: "ğŸ“ŠğŸ“ˆ"
  navbar:
    left:
      - text: "Hands-on Exercises"
        href: Hands-on_Ex/hands-on-exercises.qmd
        
    right:
      - href: index.qmd
        text: ğŸ ï¸ 
      - href: about.qmd
        text: ğŸ™‹â€â™€ï¸

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: full
    smooth-scroll: true
    font-family: "Roboto"

editor: visual

